# Generated by Django 4.2.7 on 2023-11-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_auto_20220417_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='images/sliders', verbose_name='تصویر اسلایدر(2160\u200a×\u200a972)'),
        ),
    ]
